apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: app-name
      type: string
      default: counters-api
    - name: build-image
      type: string
      default: image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/counters-api:latest
  workspaces:
    - name: source
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: source
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: source
          workspace: source
      params:
        - name: url
          value: "$(params.repo-url)"
    - name: lint
      taskRef:
        name: flake8   # if you have a flake8 Task installed from the catalog
      workspaces:
        - name: source
          workspace: source
    - name: test
      runAfter:
        - lint
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: source
    - name: build
      runAfter:
        - test
      taskRef:
        name: buildah   # assumes buildah Task is installed
      workspaces:
        - name: source
          workspace: source
      params:
        - name: IMAGE
          value: "$(params.build-image)"
    - name: deploy
      runAfter:
        - build
      taskRef:
        name: openshift-client   # assumes this Task is installed
      workspaces:
        - name: source
          workspace: source
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -
